### ISSUE TITLE
Help compiling on Debian Stretch (9.6)?

### ISSUE THREAD

**Issue by bs27975** [Necronhym/Pixel_Search#1]
Thank you for the file comment of:
// g++ <name>.cxx -o <name> -lXlib

however it would not let me compile. [I've since lost the error message.]

It seems that 'sudo apt-get libx11-dev' is the appropriate incantation, but I am still unable to compile.

The only Xlib.so I could find on my system is in /usr/lib/x86_64-linux-gnu/perl5/5.24/auto/Tk/Xlib/Xlib.so

g++ c.cxx -o Pixel_search -l Xlib -L /usr/lib/x86_64-linux-gnu/perl5/5.24/auto/Tk/Xlib

returns:
/usr/bin/ld: cannot find -lXlib
collect2: error: ld returned 1 exit status

Suggestions would be very welcome.

(Additional lines to the //g++ comment line would be very useful.)

**Comment by Necronhym** [comment]
Due to recent changes in X11 in Debian 9 some libraries have been moved around.
As such -lxlib has been replaced with -lX11.
Doing: "g++ c.cxx -o c -lX11" Should fix your compiling error.
This has how been fixed in the code displayed on the Github page.
Thank your for your feedback

Cheers.
