### ISSUE TITLE
Related info.

### ISSUE THREAD

**Issue by bs27975** [Necronhym/Pixel_Search#2]
On a related note:

https://translate.google.com/translate?sl=auto&tl=en&u=https%3A%2F%2Fforum.ubuntuusers.de%2Ftopic%2Fpixelsearch-funktion-fuer-bash-skript%2F

seems useful and topical.

**Comment by Necronhym** [comment]
I've done this with bash before as well, thank you for the resources.
However this pixel search function is part of a larger peace of software written mostly in C++. As such i prefer to keep all the code in a single language for the sake of consistency,
